### ISSUE TITLE
Issue Configuring mongodb+srv

### ISSUE THREAD

**Issue by blitworxUser** [steineey/node-red-contrib-mongodb4#2]
When creating a connection configuration that uses the mongodb+srv driver the UI Requires a Port Number while the driver errors because one is present.  The Port configuration input should not be required when the mongodb+srv is selected.

**Comment by steineey** [comment]
Hi, you are right. The port number should always be optional. I have fixed this in version 1.1.6, which is already published to npm.
You should now be able to connect to a DNS seed list. Just let the port field empty.
Thank you for reporting this issue.

**Comment by johncaipa** [comment]
Hi, i have v1.1.6 installed, but i can not connect to my mongocloud database with mongodb+srv url string, i have this error "connection <monitor> to xx.xx.xx.xx:27017 closed"
![image](https://user-images.githubusercontent.com/31298276/147614742-555dcb54-1034-422d-b815-e552796ac311.png)
I don't know what the problem is, I have tried other different nodes (node-red-contrib-mongodb3) and they have worked for me.

**Comment by steineey** [comment]
Hi johncaipa,
when did this error occur in your flow lifecycle? Did this occur at the start of your flow?
Please update to v1.1.9. for all latest fixes.

**Comment by johncaipa** [comment]
Hi steineey, yes this happens shortly after deploying the flow, at the moment I have no easy way to update to v1.1.9 in the production flow (IBM cloud nodered app), but I will try to test it in a different flow.

**Comment by johncaipa** [comment]
Hi steineey, I have tried with v1.1.9 and I get the same connection error, 
![image](https://user-images.githubusercontent.com/31298276/147666559-a6f21874-13b7-45a9-89a0-c05633fcd2d5.png)
they try to connect for a few seconds and then the message appears on the console
![image](https://user-images.githubusercontent.com/31298276/147666232-248df1ec-ecbd-4950-a89e-3670416412fd.png)
I don't know if I'm doing something wrong

**Comment by steineey** [comment]
HI johncaipa, 
this error is thrown by the underlying [MongoDB Driver](https://www.npmjs.com/package/mongodb).

There are several possible causes for a "connection closed" error. In most cases your connection was rejected by the database server. Have you white listet your node-red ip in the ip access list of your database server? Is your authentication source correct?

I think you get more information in your database server log.

You said it has already worked with node-red-contrib-mongodb3. Can you send me an example how you have defined the connection string for this node? Do you want to connect to a replica set?

**Comment by johncaipa** [comment]
Hi, this are the connection for  node-red-contrib-mongodb3 on the same flow that a i install this node, so the ip have access
![image](https://user-images.githubusercontent.com/31298276/147934372-0876a7e8-db74-4ec6-820c-1f4c988c48a9.png)
in that node I can put the complete string in a single field, the connection string are something like this:
mongodb+srv://username:password@xxxx.t5a7f.mongodb.net/database?retryWrites=true&w=majority
yes is a replica set 3 nodes.

**Comment by steineey** [comment]
Hi @johncaipa , I tried to reproduce your problem on a MongoDB Atlas Cloud Cluster and I think this is a timeout issue.
First I got the same error like you before "connection closed", then I set the connectTimeoutMS property to 30000 and the error was gone. The default connect timeout of the driver is 10 sec and my connection took around 12 sec.

I did some more improvements to the client configuration node. You can now also pass a URI string like before in node-red-contrib-mongodb3. But be aware that your credentials in this connection will be stored in clear text inside the flow.json which could be a security issue.

Here is a example configuration for v1.2.1 of this node:
<img width="642" alt="Bildschirmfoto 2022-01-03 um 21 26 42" src="https://user-images.githubusercontent.com/25723780/147976935-7d612dba-4d18-484a-90c1-9d533d884661.png">

I hope this will help you.

**Comment by johncaipa** [comment]
Thanks, now it works perfect!
