### ISSUE TITLE
Feature Request ( PUT ENV Variables in the node configuration)

### ISSUE THREAD

**Issue by DmytroMytsak** [steineey/node-red-contrib-mongodb4#27]
Hello, I really like your node, but in order to fully switch to it, the ability to dynamically pass the connection parameters to the database is not enough. Would it be difficult for you to add them? For example, in this node https://flows.nodered.org/node/node-red-node-mongodb, you can set database connection parameters with envs.

**Comment by steineey** [comment]
Hi, thank you for this feedback and your request. I'm not 100% sure if I understand what you mean.

I guess you want to use environment variable in the mongodb configuration node to set your connection options for a specific environment. This is already possible - no additional feature necessary. Just use the ${} syntax inside a config field.

This is an example for an env variable "hostname" and "username".

<img width="572" alt="Bildschirmfoto 2023-12-20 um 15 24 33" src="https://github.com/steineey/node-red-contrib-mongodb4/assets/25723780/24218fdb-dcea-4d9e-9b6f-c921acce4cd2">

I hope this fits your needs.

**Comment by DmytroMytsak** [comment]
Yes, that's exactly what I meant, but it doesn't work for me with exactly this syntax
