### ISSUE TITLE
Node loses message when passed a msg while connecting to the database. 

### ISSUE THREAD

**Issue by blitworxUser** [steineey/node-red-contrib-mongodb4#3]
Found an issue when a message is sent to the node before a connection is established the msg gets stuck and nothing is passed to the output node.  No errors are created while in this state.

**Comment by steineey** [comment]
I have fixed that in v1.1.8 (already published on npm).
You can now send request messages to the node before the database connection is established. The node will execute these requests after the connection was successful. If the connection fails these messages will be dropped and the node sends an error.
Thank you for posting this issue.
