### ISSUE TITLE
findOneAndUpdate with { returnOriginal: false } still returns the old document

### ISSUE THREAD

**Issue by avacom** [steineey/node-red-contrib-mongodb4#30]
```
msg.payload = [
    {
       id: msg.rip_leave_request.id 
    },
    {
        $set: {
            RMAssignmentID: msg.rm_leave_request.id,
            RMUserID: msg.rm_leave_request.user_id
        }
    },
    { returnOriginal: false }
];
```

when I pass this message to the mongo4 node, the update is performed, however, the old document is returned. When I do the same from the Mongo shell, it correctly returns the updated document.

Could you please advise? Thanks a lot

**Comment by steineey** [comment]
Hi, 
sry for the late reply.
The mongodb driver in nodejs does not always behave exactly like the shell. In many cases input arguments are different and also the output may a different one compared to the shell.
What operation do you use: updateOne or findOneAndUpdate. Read [here](https://mongodb.github.io/node-mongodb-native/5.9/classes/Collection.html) about all the supported collection operations.
