### ISSUE TITLE
Use ObjectId in filters

### ISSUE THREAD

**Issue by JbIPS** [steineey/node-red-contrib-mongodb4#5]
Hi!

I just tried your node to connect to my MongoDB but I'm unable to create a document with a default Id (so an `ObjectId` in MongoDB) and get it back with the outputted ID.

I think it's because the ID is not wrapped into an `ObjectId` but I can't force it in the `msg.payload` since it gives an `Invalid JSON` error.

Is there a trick to do it or should I manually set IDs in order to find them later?

Thank you, great work!

**Comment by steineey** [comment]
Hi,
you have to use an `ObjectId` in your query statement to query for the default _id.
At the moment the operation node will not help you out with this. This could be a feature in a future release.

Meanwhile you can do this:

1. Open the `~/.node-red/settings.js` file and add mongodb to your `functionGlobalContext`
```
functionGlobalContext: {
        mongodb: require('mongodb')
},
```
This will give you access to the mongodb driver inside a function node. Save the settings.js file and restart your node-red.

2. Go to the function node where you set the query statement for a findOne operation.
```
const {ObjectId} = global.get('mongodb');
msg.payload = [{_id: ObjectId(msg.payload.insertedId)}];
return msg;
```
`global.get('mongodb')` gives you access to the mongodb driver, which includes an `ObjectId` factory.


I created this small example flow, where I inserted a document and read the same document after insertion.
```
[{"id":"4a63ca89c3b21027","type":"tab","label":"Example ObjectId","disabled":false,"info":"","env":[]},{"id":"e9f3a2e6d438b379","type":"inject","z":"4a63ca89c3b21027","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":130,"y":120,"wires":[["916da41a12ef0959"]]},{"id":"916da41a12ef0959","type":"function","z":"4a63ca89c3b21027","name":"set insert","func":"msg.payload = [{name: 'marina', age: 25}];\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":290,"y":120,"wires":[["3b30961d11e59f16"]]},{"id":"3b30961d11e59f16","type":"mongodb4","z":"4a63ca89c3b21027","clientNode":"e2bc7ac9aa77279e","collection":"persons","operation":"insertOne","output":"toArray","name":"","x":440,"y":120,"wires":[["a798900de2d6139f"]]},{"id":"c0b30eac41ad9309","type":"debug","z":"4a63ca89c3b21027","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":970,"y":120,"wires":[]},{"id":"a798900de2d6139f","type":"function","z":"4a63ca89c3b21027","name":"set find query","func":"const {ObjectId} = global.get('mongodb');\nmsg.payload = [{_id: ObjectId(msg.payload.insertedId)}];\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":620,"y":120,"wires":[["6fe73f937a1ce895"]]},{"id":"6fe73f937a1ce895","type":"mongodb4","z":"4a63ca89c3b21027","clientNode":"e2bc7ac9aa77279e","collection":"persons","operation":"findOne","output":"toArray","name":"","x":800,"y":120,"wires":[["c0b30eac41ad9309"]]},{"id":"e2bc7ac9aa77279e","type":"mongodb4-client","name":"simple connection","protocol":"mongodb","hostname":"localhost","port":"","dbName":"nodered","authSource":"nodered","authMechanism":"SCRAM-SHA-256","tls":false,"tlsCAFile":"","tlsInsecure":false,"uri":"","advanced":"{\"connectTimeoutMS\": 30000}","uriTabActive":"tab-uri-simple"}]
```

**Comment by JbIPS** [comment]
> Another useful note:
A outputted _id from the operation node like insertedId or any document _id is not a string like the node-red debug console displays it. It's an ObjectId. And you don't need to wrap it in ObjectId for further request.

Very useful indeed! Thank you very much for the help!
