### ISSUE TITLE
Update multiple documents by IDs

### ISSUE THREAD

**Issue by jaroslavhuss** [steineey/node-red-contrib-mongodb4#6]
Dear Author, 

I am absolutely lost - could you make an example how to make updateMany by id? I was trying even raw queries yet I am still falling into some error. 

I was trying to do something like this: 
msg.query
`[
  {
    "id": { "$in": ["6242170245341c11dc2133da", "6242173e45341c11dc2133dc"] }
  }
]
`
and msg.payload

`
{wasSent:true}
`

I am lost and exhausted already :-) 

Thank you!

**Comment by steineey** [comment]
hi,
first of all you have to set `msg.payload` for your query arguments ;-)
After that you have to use the mongodb-driver ObjectId to do an operation with the document id ("_id").
Document Id's aren't strings like the node-red debugging console displays it. 

Inside a function node prepare the query like so:
```
var {ObjectId} = global.get('mongodb');
msg.payload = [{ _id: { $in: [ ObjectId('6242170245341c11dc2133da'), ObjectId('6242170245341c11dc2133da')] } }]
```
Before this you need to add mongodb to your global function context.

I explained the whole ObjectId topic more detailed in this [issue](https://github.com/steineey/node-red-contrib-mongodb4/issues/5)

I´m currently working on an update for this node which will handle the ObjectId implicit for you. But for now you have to set your document id explicit with ObjectId.

With the upcoming update i will also release more example flows with updateMany and other more complex queries.

**Comment by steineey** [comment]
hi,

I release v1.3.0 which is enabled to handle _id with string values.
I also added more examples [here](https://github.com/steineey/node-red-contrib-mongodb4/blob/master/examples/example-1.json).

Please send me your flow.json, if you still lost ;-)

I will close this issue for know.
